import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';

import { ThemeProvider } from 'next-themes';

import '@/app/globals.css';

// Import Source Sans Pro from Google Fonts
const sourceSansPro = Source_Sans_3({
    subsets: ['latin'],
    variable: '--font-source-sans-pro',
    weight: ['200', '300', '400', '500', '600', '700', '900'],
    display: 'swap'
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        // ? https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
        // ? https://react.dev/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors
        <html suppressHydrationWarning lang='en'>
            <body className={`${sourceSansPro.variable} bg-background text-foreground antialiased`}>
                <ThemeProvider attribute='class'>{children}</ThemeProvider>
            </body>
        </html>
    );
};

export default Layout;
